name = "cursor-to-openai"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV 绑定配置 - 用于存储令牌和配置
# 在实际使用前，需要先创建 KV 命名空间:
# wrangler kv:namespace create TOKEN_STORE
# 然后将生成的 id 替换到下面
# [kv_namespaces]
# binding = "TOKEN_STORE"
# id = "替换为你创建的命名空间ID"

[vars]
# 可以在这里设置环境变量
DEFAULT_PASSWORD = "123" 